# Generated by Django 5.2.4 on 2025-07-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(choices=[('EXT', 'EXT'), ('INT', 'INT'), ('Common', 'Common')], default='Common', max_length=32)),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=32)),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.phase')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.workcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Subproject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_edding', models.BooleanField(default=False)),
                ('people', models.ManyToManyField(blank=True, related_name='subprojects', to='api.person')),
            ],
        ),
        migrations.AddField(
            model_name='phase',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='api.subproject'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('waiting', 'waiting'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', max_length=32)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.asset')),
                ('people', models.ManyToManyField(blank=True, related_name='tasks', to='api.person')),
            ],
        ),
        migrations.CreateModel(
            name='Workload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=1, max_digits=5)),
                ('people', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='api.task')),
            ],
        ),
    ]
