# Generated by Django 5.2.4 on 2025-08-26 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(default='255, 255, 255', max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='people',
            new_name='assignees',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='is_edding',
        ),
        migrations.AddField(
            model_name='person',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='api.person'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='editing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='editing_subprojects', to='api.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='people', to='api.department'),
        ),
        migrations.CreateModel(
            name='PersonWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('week', models.DateField()),
                ('man_week', models.DecimalField(decimal_places=1, max_digits=5)),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.person')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workloads', to='api.task')),
            ],
        ),
        migrations.CreateModel(
            name='PMMWorkload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('week', models.DateField()),
                ('man_week', models.DecimalField(decimal_places=1, max_digits=5)),
                ('subproject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmm_workloads', to='api.subproject')),
                ('work_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pmm_workloads', to='api.workcategory')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='api.step'),
        ),
        migrations.DeleteModel(
            name='Workload',
        ),
    ]
