# Generated by Django 5.2.4 on 2025-09-04 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_department_step_rename_people_task_assignees_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='status',
        ),
        migrations.RemoveField(
            model_name='subproject',
            name='people',
        ),
        migrations.AddField(
            model_name='person',
            name='subproject',
            field=models.ManyToManyField(blank=True, related_name='people', to='api.subproject'),
        ),
        migrations.AddField(
            model_name='phase',
            name='milestone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='phase',
            name='type',
            field=models.CharField(choices=[('DESIGN', 'DESIGN'), ('PRODT', 'PRODT'), ('ENG', 'ENG')], default='DESIGN', max_length=32),
        ),
        migrations.AddField(
            model_name='subproject',
            name='access',
            field=models.CharField(choices=[('Common', 'Common'), ('Project Team', 'Project Team'), ('High Confidential', 'High Confidential')], default='Project', max_length=32),
        ),
        migrations.AddField(
            model_name='subproject',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subprojects', to='api.department'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('wtg', 'wtg'), ('ip', 'ip'), ('fin', 'fin')], default='wtg', max_length=32),
        ),
    ]
