# Generated by Django 5.2.4 on 2025-09-04 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_asset_status_remove_subproject_people_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='pmm_status',
            field=models.CharField(choices=[('planning', 'planning'), ('approved', 'approved')], default='planning', max_length=32),
        ),
        migrations.CreateModel(
            name='MilestoneTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('milestone_type', models.CharField(choices=[('Date Receive', 'Date Receive'), ('Date Release', 'Date Release'), ('Review', 'Review'), ('DR', 'DR')], default='Review', max_length=32)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_tasks', to='api.asset')),
            ],
        ),
    ]
