# Generated by Django 5.2.4 on 2025-09-10 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_subproject_pmm_status_milestonetask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='type',
            new_name='asset_type',
        ),
        migrations.RenameField(
            model_name='phase',
            old_name='type',
            new_name='phase_type',
        ),
        migrations.AlterField(
            model_name='subproject',
            name='access',
            field=models.CharField(choices=[('Common', 'Common'), ('Project Team', 'Project Team'), ('High Confidential', 'High Confidential')], default='Project Team', max_length=32),
        ),
    ]
