# Generated by Django 5.2.4 on 2025-09-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_type_asset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subproject',
            name='last_edit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
